version: '3.4'

services:
  memberservice:
    image: ${DOCKER_REGISTRY}memberservice
    build:
      context: .
      dockerfile: Member-API/MemberService/Dockerfile


  scheduleapi:
    image: ${DOCKER_REGISTRY}scheduleapi
    build:
      context: .
      dockerfile: Schedule-API/Schedule-API/Dockerfile

