version: '3'

services:
  memberservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
      environment:
        SA_PASSWORD: "Asd132!!"
        ACCEPT_EULA: "Y"

